### ISSUE TITLE
KeyError: 'TESTING_GUILD'

### ISSUE THREAD

**Issue by vektorline** [Breq16/flask-discord-interactions#1]
Hi,

It seems there's in an error with the `discord.update_slash_commands(guild_id=os.environ["TESTING_GUILD"])` you have in your example. When added, it prevents Flask to run...

Without it, I wasn't able to also have the bot going live on Discord... so wondering if this is related to this specific issue or there's another part I missed...

**Comment by vektorline** [comment]
Forgot to add, the `pip install Flask-Discord-Interactions==0.1.3` is returning an error... I guess this is more a PyPi issue?

**Comment by Breq16** [comment]
The example assumes that you have an environment variable set called `TESTING_GUILD` that has the ID of the server you want to deploy to.

This is to get around a limitation of Discord: if you register a command globally, it will take up to an hour to register, but if you specify a guild ID, it will update for that specific guild instantly. The Discord [docs](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) will tell you how to get the server ID. Then you could either set that environment variable, or just replace that line with something like `discord.update_slash_commands(guild_id="197777408198180864")` (but replace the ID number with whatever your server's is of course).

What is the error you're getting with PyPi? I just tested re-installing it in a clean environment without any issues, but I'm kind of a noob to PyPi packaging so there's a chance I messed something up.

**Comment by vektorline** [comment]
Thanks!  
When I add the guild_id, I'm getting some errors and Flask isn't loading. If I remove it works and the rest of my Flask App is working, but the Bot isn't going online... or I don't know then how I can send it a basic ping request from discord... Sorry noob here.

Error below if I set guild_id in the update_slash (took out guild id & app id from it)

`[Mon Jan 11 10:44:41.032978 2021] [wsgi:error] [pid 8239:tid 2989487136] [client 34.75.59.10:15272]   File "/home/vic/dev/discord/discord/lib/python3.7/site-packages/flask_discord_interactions/discord.py", line 100, in update_slash_commands
[Mon Jan 11 10:44:41.033050 2021] [wsgi:error] [pid 8239:tid 2989487136] [client 34.75.59.10:15272]     response.raise_for_status()
[Mon Jan 11 10:44:41.033131 2021] [wsgi:error] [pid 8239:tid 2989487136] [client 34.75.59.10:15272]   File "/home/vic/dev/discord/discord/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
[Mon Jan 11 10:44:41.033280 2021] [wsgi:error] [pid 8239:tid 2989487136] [client 34.75.59.10:15272]     raise HTTPError(http_error_msg, response=self)
[Mon Jan 11 10:44:41.033399 2021] [wsgi:error] [pid 8239:tid 2989487136] [client 34.75.59.10:15272] requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://discord.com/api/v8/applications/<appid>/guilds/<guildid>/commands`


---
See the error attached for the Pypi
<img width="648" alt="Screenshot 2021-01-11 at 10 30 07" src="https://user-images.githubusercontent.com/76811421/104164326-0c66f180-53f8-11eb-81eb-ff551b2c81d1.png">

(That could be...)

**Comment by Breq16** [comment]
No worries! I probably should have written more about the process of setting everything up in the README. I'll try to get to that soon.

Okay, so you're getting a `403 Forbidden` error when the code attempts to update the slash commands. That would suggest you need to authorize your bot to use slash commands in whatever server you are testing in.

Go to the Discord Developer Portal, click OAuth2 on the left, tick the "applications.commands" box, and go to the URL. (not the "bot" one, that is for WebSocket gateway based bots).
![image](https://user-images.githubusercontent.com/13875971/104224887-96708380-5413-11eb-8b9a-b54efc0711a7.png)

That should take you to a page where you can authorize your bot to add slash commands to your server.
![image](https://user-images.githubusercontent.com/13875971/104225002-c586f500-5413-11eb-82d4-80acf113a6d2.png)

Once you select a server and click "Authorize", the bot should be able to add slash commands to that server.

In regards to PyPI, what version of Python do you have installed? I think I might've only published the PyPI package for versions 3.8 and up.

**Comment by vektorline** [comment]
Sweet thanks for the detailed answer. It's working like a charm, thanks! Now I need to figure out how to enable this in DM.

For Pypi, I guess it's beecause I'm on 3.7

**Comment by Breq16** [comment]
That's good to hear!

Unfortunately, it looks like Discord doesn't support slash commands in DMs yet (see: https://github.com/discord/discord-api-docs/issues/2365). It does say support is planned though. In the meantime I guess only traditional bots are supported in DMs.
