### ISSUE TITLE
User commands don't work on non-members

### ISSUE THREAD

**Issue by Miner3089** [Breq16/flask-discord-interactions#105]
**Describe the bug**
Attempting to use a context menu user command on a user that is not a member of the server will result in an error. The same issue also occurs when attempting to use a user command in the bot's DMs.

**Categorization**
This issue impacts...
- [x] The library itself
- [ ] Documentation
- [ ] Examples

**To Reproduce**
1. Create a context menu user command.
2. Attempt to use the command on a user that is not a member of the server or in the bot's DMs.

**Expected behavior**
The context menu command should work as normal, without any errors.

**Environment**
I am using... (check any that apply, leave unchecked if you don't know)
- [ ] Quart and/or Asyncio
- [ ] A "Bot User"
- [ ] Additional Flask extensions (SQLAlchemy, Flask-CORS, etc.)
- [ ] Additional backend services (Redis, RQ, Celery)

**Additional context**
This can easily be fixed by modifying the [`parse_target`](https://github.com/Breq16/flask-discord-interactions/blob/main/flask_discord_interactions/context.py#L241) function in the [`context.py`](https://github.com/Breq16/flask-discord-interactions/blob/main/flask_discord_interactions/context.py) file with the following code.
```py
if self.target_id in self.members:
    self.target = self.members[self.target_id]
else:
    self.target = self.users[self.target_id]
```

**Comment by Breq16** [comment]
How are you able to use user or message commands in DMs? I'm trying to reproduce this issue but I can't find a way of triggering the user command from the client (the "Apps" dropdown doesn't appear at all).

**Comment by Miner3089** [comment]
The application commands need to be global commands to appear in the bot's DMs; they seem to appear for me in DMs both on desktop and mobile. I haven't tested with message commands, however they don't seem to be affected by this bug. The bug is also reproducible by using a user command on a user that is not a member of the server, it will result in a KeyError because `self.members` is empty if the user command is used on a non-member or in the bot's DMs.

**Comment by Breq16** [comment]
> The application commands need to be global commands to appear in the bot's DMs

Oops, yep, that was the part I missed. Thanks for the clarification! I'll be pushing out a release with this and a few other bugfixes shortly.
