### ISSUE TITLE
Getting a HTML error 400 for some reason...

### ISSUE THREAD

**Issue by sirix123** [Breq16/flask-discord-interactions#128]
**Describe the bug**
My website crashed the other day with this messsage, i have rotated all the tokens etc and still not working, i haven ttouched the code for months

`2024-02-02 03:34:57,100: Error running WSGI application
2024-02-02 03:34:57,104: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discord.com/api/v10/oauth2/token
2024-02-02 03:34:57,104:   File "/var/www/www_sdgames_co_wsgi.py", line 20, in <module>
2024-02-02 03:34:57,104:     from run import app as application # noqa from app
2024-02-02 03:34:57,104: 
2024-02-02 03:34:57,104:   File "/home/sirix123/sd-games-web-app/run.py", line 6, in <module>
2024-02-02 03:34:57,104:     app = create_app()
2024-02-02 03:34:57,105: 
2024-02-02 03:34:57,105:   File "/home/sirix123/sd-games-web-app/app/__init__.py", line 60, in create_app
2024-02-02 03:34:57,105:     discord.update_commands(guild_id=os.environ.get('SERVER_GUID'))
2024-02-02 03:34:57,105: 
2024-02-02 03:34:57,105:   File "/home/sirix123/.virtualenvs/myvirtualenv2/lib/python3.9/site-packages/flask_discord_interactions/discord.py", line 425, in update_commands
2024-02-02 03:34:57,105:     url, json=overwrite_data, headers=self.auth_headers(app)
2024-02-02 03:34:57,105: 
2024-02-02 03:34:57,105:   File "/home/sirix123/.virtualenvs/myvirtualenv2/lib/python3.9/site-packages/flask_discord_interactions/discord.py", line 384, in auth_headers
2024-02-02 03:34:57,105:     DiscordInteractions.fetch_token(app)
2024-02-02 03:34:57,106: 
2024-02-02 03:34:57,106:   File "/home/sirix123/.virtualenvs/myvirtualenv2/lib/python3.9/site-packages/flask_discord_interactions/discord.py", line 360, in fetch_token
2024-02-02 03:34:57,106:     response.raise_for_status()
2024-02-02 03:34:57,106: 
2024-02-02 03:34:57,106:   File "/home/sirix123/.virtualenvs/myvirtualenv2/lib/python3.9/site-packages/requests/models.py", line 940, in raise_for_status
2024-02-02 03:34:57,106:     raise HTTPError(http_error_msg, response=self)`

my code:
```
import os

from dotenv import load_dotenv
from flask import Flask, redirect, render_template
from flask_sqlalchemy import SQLAlchemy

from .config import ProductionConfig, DevelopmentConfig
from .models.db_controls import DBController

load_dotenv()

# config init
if os.environ.get('THIS_ENV', 'DevelopmentConfig') == 'ProductionConfig':
    config = ProductionConfig
else:
    config = DevelopmentConfig

#  db init
db = SQLAlchemy()
db_controller = DBController()

# discord lib
from flask_discord_interactions import DiscordInteractions

# app init
def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    #  discord int
    discord = DiscordInteractions(app)

    db.init_app(app)

    # db_controller will now handle database ops, you can add to this further.
    db_controller.init_app(app, db)

    # db_controller methods can be passed application context if needed.
    # The app context is only needed if the action is not within a defined route.
    db_controller.create_all(include_context=True)

    # Importing of views is handed to the blueprint. View the __init__.py file in the
    # blueprint to see how this is working.
    def import_blueprints():
        from app.blueprints.home import home
        from app.blueprints.poe_leaderboard import poe_leaderboard
        from app.blueprints.scripts import scripts
        from app.blueprints.poe_leaderboard.poe_bot import bp as echo_bp
        from app.blueprints.moodler import moodler
        app.register_blueprint(home)
        app.register_blueprint(poe_leaderboard)
        app.register_blueprint(scripts)
        app.register_blueprint(moodler)
        discord.register_blueprint(echo_bp)

    import_blueprints()

    if config != DevelopmentConfig:
        discord.set_route("/interactions")
        discord.update_commands(guild_id=os.environ.get('SERVER_GUID'))

    @app.get('/')
    def index():
        return render_template('home/index.html')
    
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('home/index.html')

    # print url_map, this prints all the routes in the terminal
    print(app.url_map)

    return app
```

**Comment by breqdev** [comment]
Looks like the same thing as #126. Seems very confusing to me as there's nothing new in the changelog recently: https://discord.com/developers/docs/change-log

Like you, I also have not touched this code for months :) and to be honest I can't promise when I'll have a chance to look into this further, but I'll keep this updated if I figure this out.

**Comment by maddie480** [comment]
Hi, I've got the same issue yesterday on my own stuff and was as confused as you 😅 Apparently you need to pass the `client_id` and `client_secret` in the request body now. Not sure if this is intended though, since the docs weren't updated 🤔

**Comment by sirix123** [comment]
I think this part needs to be updated:

```
 @static_or_instance
    def fetch_token(self, app: Flask = None):
        """
        Fetch an OAuth2 token from Discord using the ``CLIENT_ID`` and
        ``CLIENT_SECRET`` with the ``applications.commands.update`` scope. This
        can be used to register new application commands.

        Parameters
        ----------
        app
            The Flask app with the relevant config (client ID and secret).
        """

        if app is None:
            app = self.app

        if app.config["DONT_REGISTER_WITH_DISCORD"]:
            app.discord_token = {
                "token_type": "Bearer",
                "scope": app.config["DISCORD_SCOPE"],
                "expires_in": 604800,
                "access_token": "DONT_REGISTER_WITH_DISCORD",
            }
            app.discord_token["expires_on"] = (
                time.time() + app.discord_token["expires_in"] / 2
            )
            return

        response = requests.post(
            app.config["DISCORD_BASE_URL"] + "/oauth2/token",
            data={
                "grant_type": "client_credentials",
                "scope": app.config["DISCORD_SCOPE"],
            },
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            auth=(app.config["DISCORD_CLIENT_ID"], app.config["DISCORD_CLIENT_SECRET"]),
        )

        response.raise_for_status()
        app.discord_token = response.json()
        app.discord_token["expires_on"] = (
            time.time() + app.discord_token["expires_in"] / 2
        )
 ```
 
 I'm not that familar with the code base though, happy to make the change and do a pull request though.

**Comment by maddie480** [comment]
Just opened an issue on Discord's end: https://github.com/discord/discord-api-docs/issues/6639

**Comment by breqdev** [comment]
Appears this is being fixed on their end: https://github.com/discord/discord-api-docs/issues/6639#issuecomment-1924245970

**Comment by breqdev** [comment]
Discord claims to have implemented a fix: https://github.com/discord/discord-api-docs/issues/6639#issuecomment-1924475985. Feel free to reopen this issue if the problem still occurs.
