### ISSUE TITLE
Embeds in Ephemeral Messages soon to be supported

### ISSUE THREAD

**Issue by TheJaffaMeme** [Breq16/flask-discord-interactions#19]
Mentioned [here](https://github.com/discord/discord-api-docs/issues/2318#issuecomment-829189729) ephemeral embeds are soon to be supported so you may want to keep this in mind as this library checks for embeds in an ephemeral message and throws an error.

**Comment by Breq16** [comment]
Thanks for the heads up! This should be patched in 1c73244. I'll push a release out soon as well :+1:
