### ISSUE TITLE
Sending multiple Embeds results in no error but they don't get sent

### ISSUE THREAD

**Issue by milan252525** [Breq16/flask-discord-interactions#26]
I'm sending multiple embeds with this code:
```python
@discord.command(annotations={"region": "Choose region"})
def region(ctx, region: Regions):
    "Clubs from region"
    #gets list of dictionaries to process
    clubs = get_data.get_clubs(region=region, country=None, type=None, members=None)
    #makes list of embeds (max 10, all dont exceed any limit)
    embeds = clubs_to_embeds(clubs, f"Title")
    return Response(embeds=embeds)
```
When I send one or two embeds everything is fine and they get sent. 
But when the embeds get longer or there are more of them, slash command in Discord stays stuck at "Sending command..." and unfortunately no error appears.

I'm making sure no embed exceeds character limits and there are not more than 10 of them.
I wasn't able to find any other limit mentioned in [docs](https://discord.com/developers/docs)
When I send them separtely as followup responses they do get sent fine.

**Comment by Breq16** [comment]
The [embed limits](https://discord.com/developers/docs/resources/channel#embed-limits) include:
> Additionally, the characters in all title, description, field.name, field.value, footer.text, and author.name fields must not exceed 6000 characters in total. Violating any of these constraints will result in a Bad Request response.

This includes the `title`, `description`, and other fields across *all* of the embeds in the message, not just each one. So, if I try to send 10 embeds with 700 characters each in a single message, that's a total of 7000 characters, which breaks the limit. In other words, the 6000 character limit applies to all of the embeds combined, not just each embed individually.

(This limit is badly worded, I know... to be honest I had to actually try some embeds for myself to see what the Discord API did, but I was able to reproduce the issue that you mentioned. It's a shame that Discord doesn't give you any useful error message, but it's kind of just the way slash command errors work for now.)
