### ISSUE TITLE
Sub Command Group Context Issue

### ISSUE THREAD

**Issue by jethrob** [Breq16/flask-discord-interactions#29]
When trying to access the ctx (Context) from a sub command, it looks like the Context isn't being passed correctly.

I noticed this when trying to access the "display_name" property.
![image](https://user-images.githubusercontent.com/1051270/124108896-e1845e80-da66-11eb-981e-79f171c57643.png)

Here is a screenshot of the properties and value.
![image](https://user-images.githubusercontent.com/1051270/124108699-ae41cf80-da66-11eb-9b57-302c1dd6aa0a.png)

If you need any other info please let me know, or if I am doing something wrong.

**Comment by Breq16** [comment]
Thank you for the detailed report! I was able to reproduce the issue you described with the Context object.

I have merged in a fix and published a new release to PyPI (v0.1.12). Let me know if you still experience any problems.

**Comment by jethrob** [comment]
Thanks, appreciate it.
