### ISSUE TITLE
Command not registering 

### ISSUE THREAD

**Issue by Instra1** [Breq16/flask-discord-interactions#57]
Hello, I'm trying to make a __simple__ command using ```@discord.command()
def ping(ctx):
    "Respond with a friendly 'pong'!"
    return "Pong!"``` and it just won't register, I've tried kicking the bot & reinventing it, ect. Please fix this issue!

**Comment by Instra1** [comment]
# @Breq16

**Comment by Breq16** [comment]
Do you get any error messages?

Have you followed the [https://flask-discord-interactions.readthedocs.io/en/latest/botsetup.html](tutorial)?

**Comment by Instra1** [comment]
> Do you get any error messages?
> 
> Have you followed the [https://flask-discord-interactions.readthedocs.io/en/latest/botsetup.html](tutorial)?

No I don't get any errors the slash commands just don't show up or register and yes I followed

**Comment by Breq16** [comment]
Are you attempting to register guild-specific commands or global commands? Global commands can take up to 1 hour to roll out, as per [Discord docs](https://discord.com/developers/docs/interactions/application-commands#making-a-global-command).

**Comment by Breq16** [comment]
Additionally, you might be getting rate-limited, this can cause your program to appear frozen for a bit before the `Listening on...` message appears. Do you see a message like this?
```
 * Serving Flask app 'ping' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 ```

**Comment by Breq16** [comment]
Closing this for now due to inactivity, feel free to reopen if you still experience this issue.
