### ISSUE TITLE
Can't define commands permissions in groups and subgroups

### ISSUE THREAD

**Issue by EpocDotFr** [Breq16/flask-discord-interactions#65]
Hi! Thank you very much for Flask-Discord-Interactions, sent you some bucks 😉 

The [DiscordInteractions.command](https://flask-discord-interactions.readthedocs.io/en/latest/discord.html#flask_discord_interactions.DiscordInteractions.command) decorator allows to define permissions for a given command. However, [SlashCommandGroup.command](https://flask-discord-interactions.readthedocs.io/en/latest/command.html#flask_discord_interactions.SlashCommandGroup.command) and [SlashCommandSubgroup.command](https://flask-discord-interactions.readthedocs.io/en/latest/command.html#flask_discord_interactions.SlashCommandSubgroup.command) can't.

Is there a reason one couldn't define permissions when using those last two? I may be missing something, if so, apologize in advance.

**Comment by Breq16** [comment]
Hi!

First of all, thank you so much for sponsoring my work! I'm really glad you find it useful. :grin:

To answer your question, this is a limitation on Discord's end. The explanation for why this is the case is a bit convoluted, but I'll do my best:

In short, subcommands are actually handled as ["options"](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure) for the base command, similar to a string option, user option, etc. When you construct a `SlashCommandGroup` or `SlashCommandSubgroup` in Flask-Discord-Interactions, it will actually be translated into a base command with `SUB_COMMAND` or `SUB_COMMAND_GROUP` options.

On Discord's end, permissions are represented by ["permissions objects,"](https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object) which are stored separately from the command and its options. Permissions objects are linked to the command by its ID. Subcommands aren't proper commands, so they don't have IDs, and it's impossible to apply a set of permissions to one specifically.

Thanks for bringing this to my attention actually--this should really be mentioned on the "permissions" page in the documentation. Also, it *should* be possible to set permissions for an entire command group, but that hasn't been implemented in the library. I'm not sure if that would solve your specific use case, but I'll probably push a release with that functionality in the next couple days.

You can also always handle the permissions yourself, like in [this code example](https://github.com/Breq16/flask-discord-interactions/issues/21#issuecomment-857165305). It's not an ideal solution, but it's a possible workaround. Discord also tracks feature requests for their API on their [discord-api-docs](https://github.com/discord/discord-api-docs/issues) issue tracker. I don't see any issues relating to subcommand permissions, but if you want this functionality, that would be the place to ask for it.

Best of luck with whatever you're building, and let me know if you run into any more issues or have any more questions!

Thanks,
Brooke

**Comment by EpocDotFr** [comment]
> First of all, thank you so much for sponsoring my work! I'm really glad you find it useful. 😁

You're welcome!

> To answer your question, this is a limitation on Discord's end. The explanation for why this is the case is a bit convoluted, but I'll do my best:
> 
> In short, subcommands are actually handled as "options" for the base command, similar to a string option, user option, etc. When you construct a SlashCommandGroup or SlashCommandSubgroup in Flask-Discord-Interactions, it will actually be translated into a base command with SUB_COMMAND or SUB_COMMAND_GROUP options.
> 
> On Discord's end, permissions are represented by "permissions objects," which are stored separately from the command and its options. Permissions objects are linked to the command by its ID. Subcommands aren't proper commands, so they don't have IDs, and it's impossible to apply a set of permissions to one specifically.

Your explanation is very clear, now I understand.

> Thanks for bringing this to my attention actually--this should really be mentioned on the "permissions" page in the documentation.

Was about to also suggest this, doc will be even better.

> Also, it should be possible to set permissions for an entire command group, but that hasn't been implemented in the library.

My use case is the following:

  - I have a set A of admin-specific commands, some of which are dispatched into command groups and subgroups
  - I have a set B of publicly-accessible commands, some of which are also dispatched into command groups and subgroups, but aren't concerned by permissions

The issue is that I can set admin permissions on a "root" command in set A (i.e a command which isn't defined in a group or subgroup), but not in commands in set A which are dispatched intro groups and subgroups.

> I'm not sure if that would solve your specific use case, but I'll probably push a release with that functionality in the next couple days.

That would definitively solve my use case but don't worry, nothing urgent. Also I have read Discord's docs, it's nowhere mentioned permissions may be defined for entire groups or subgroups (but again, I may miss something ^^).

Thanks!

**Comment by Breq16** [comment]
This functionality should be available in v1.2.1, which you can install with `pip3 install --upgrade Flask-Discord-Interactions`. Feel free to reopen this if you still experience issues!

**Comment by EpocDotFr** [comment]
Will test ASAP, I'll keep you updated. Thanks!

**Comment by EpocDotFr** [comment]
Awesome, it's working perfectly fine 👌

![image](https://user-images.githubusercontent.com/2053431/147206555-779a12fc-f992-454d-b1f3-652c4738c451.png)

Thank you again, really looking forward releasing version 2 of my bot to my users 😄
