### ISSUE TITLE
dm people

### ISSUE THREAD

**Issue by MaskDuck** [Breq16/flask-discord-interactions#82]
**Is your feature request related to a problem? Please describe.**
i am kinda confused to dm someone myself

**Describe the solution you'd like**
a native method to dm people, possiblity `User.send`
**Describe alternatives you've considered**
trying to use the raw api

**Additional context**

**Comment by Breq16** [comment]
This library uses the Webhook API to respond to interactions. The rationale for this is documented [here](https://flask-discord-interactions.readthedocs.io/en/latest/#how-is-this-different-from-discord-py-slash-command). As such, you can only respond to a command in a few ways, [listed here](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type).

If you just want to run commands in a DM, this is documented [here](https://flask-discord-interactions.readthedocs.io/en/latest/dm.html).

If you want your bot to DM people directly in response to a command run in a server, you need to use a library which connects to Discord using a websocket -- webhook libraries like this one can't support that feature unless Discord adds support.

If you just want to send the user a message that others in the channel can't see, consider an [ephemeral message](https://flask-discord-interactions.readthedocs.io/en/latest/message.html).

**Comment by MaskDuck** [comment]
i see. thanks for clarification.
