### ISSUE TITLE
Permissions overwrites fail to execute

### ISSUE THREAD

**Issue by Breq16** [Breq16/flask-discord-interactions#85]
**Describe the bug**
Attempting to use `ctx.overwrite_permission` fails with an HTTP 403.

**Categorization**
This issue impacts...
- [X] The library itself
- [ ] Documentation
- [ ] Examples

**To Reproduce**
1. Run the `examples/permissions.py` example.

**Expected behavior**
Command permissions overwrites are handled properly without throwing errors.

**Environment**
I am using... (check any that apply, leave unchecked if you don't know)
- [ ] Quart and/or Asyncio
- [ ] A "Bot User"
- [ ] Additional Flask extensions (SQLAlchemy, Flask-CORS, etc.)
- [ ] Additional backend services (Redis, RQ, Celery)

**Additional context**
This is related to the rollout of Permissions V2: discord/discord-api-docs#4830

**Comment by therealr5** [comment]
Same applies for `discord.update_commands() `. The route that is used there to set permissions returns a code 404.

**Comment by Breq16** [comment]
weird, it worked for me last night, i can try to look into it again in a sec

**Comment by therealr5** [comment]
That 404 only appears for global commands now. I always wondered why it was possible in the first place.

**Comment by Breq16** [comment]
Hmm, yeah, must've been a weird quirk of the v1. It seems like the best thing to do is just stop setting permissions for global commands. Should be fixed in e6887b0, I can push out a release.

**Comment by Breq16** [comment]
Looking back at this, the functionality only really worked when the bot developer happened to also be the guild admin (or someone with enough permissions). It seems like the way permission overrides are supposed to work is that the bot somehow allows guild admins to sign in, then uses _their_ bearer tokens to make any requests -- something that is probably outside the scope of this library.

I'm figuring the best course of action is probably just to stop asking for that scope and remove the permission overwrite API entirely? Especially considering it seems to be causing other issues like #112...

@therealr5 thoughts?

**Comment by therealr5** [comment]
> Looking back at this, the functionality only really worked when the bot developer happened to also be the guild admin (or someone with enough permissions). It seems like the way permission overrides are supposed to work is that the bot somehow allows guild admins to sign in, then uses _their_ bearer tokens to make any requests -- something that is probably outside the scope of this library.

Yes, something like that. The `applications.commands.permissions.update` scope is a user scope. When not used by the bot owner in the credentials grant we would have to go through a whole oauth flow to get a bearer token. With this token we can update commands with the permissions of the user we have this token for and on behalf of this user. (This permission stuff can turn out quite tricky if the user isn't an admin. Role hierarchy and channel access already caused multiple headaches for me.) In the audit logs, all permissions updates appear as if the user made them manually. I think it's almost solely designed like this with apps using a dashboard and their own permission system in mind.

> 
> I'm figuring the best course of action is probably just to stop asking for that scope and remove the permission overwrite API entirely? Especially considering it seems to be causing other issues like #112...
> 
I'd probably keep some basic stuff. While most usecases for them are replaceable using the `default_member_permissions` and manual overrides in the client, there may still be things where you need it. 
We could keep for example the `Permission` class in the code and add the channel option for it and add some basic route-wrapping methods to set permissions in case anyone uses it or its own purposes. But the methods for overwritig in the `context` class and the param while creating a command can be removed in my opinion.
