### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by bat-glitch** [Breq16/flask-discord-interactions#92]
Could the attachment option be added? I would love to use this, with this library 
https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type

**Comment by Breq16** [comment]
This library doesn't support directly returning files as a response to a command, but you can work around it with followup messages, as is done in the [followup example](https://github.com/Breq16/flask-discord-interactions/blob/946df50f6d2794a053f1d3c6da0acda2f538c3cf/examples/followup.py#L36). You can pass a tuple to the `file` argument containing the filename and the file object as documented on the [Message page](https://flask-discord-interactions.readthedocs.io/en/latest/message.html).

<details>
<summary>More details</summary>
As far as I'm aware, it's not possible to send attachments immediately as a response to a command, since response data needs to be JSON. Even if you could, the three second interaction timeout that Discord enforces would make it difficult to upload the file without exceeding the time limit. Therefore, sending a deferred message and then following up with the file is the supported way.
</details>

**Comment by bat-glitch** [comment]
> This library doesn't support directly returning files as a response to a command, but you can work around it with followup messages, as is done in the [followup example](https://github.com/Breq16/flask-discord-interactions/blob/946df50f6d2794a053f1d3c6da0acda2f538c3cf/examples/followup.py#L36). You can pass a tuple to the `file` argument containing the filename and the file object as documented on the [Message page](https://flask-discord-interactions.readthedocs.io/en/latest/message.html).
> 
> More details
> Let me know if this works for your use case!

So I tested this feature with async libraries, but they just seem to return the file url directly, so it can just send the image url, that the user requests, I just wanted to know if it was possible to make that an option for this library. Like how would the file as a option argument work for this library ?

**Comment by bat-glitch** [comment]
Like this for refrence![image](https://user-images.githubusercontent.com/69335864/169635575-cfd87bc5-2c02-42c2-8e32-fdf3f7c8073d.png)

**Comment by therealr5** [comment]
> As far as I'm aware, it's not possible to send attachments immediately as a response to a command, since response data needs to be JSON. Even if you could, the three second interaction timeout that Discord enforces would make it difficult to upload the file without exceeding the time limit. Therefore, sending a deferred message and then following up with the file is the supported way.
> 
> Let me know if this works for your use case.

According to the [discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type) it should work. I haven't played around with it yet but it seems like you can also return multipart as direct interaction response. I'll let you know if I find something out.

**Comment by therealr5** [comment]
Implementing the attachment option support should be rather easy. We get the attachment id as option value and the actual attachment structure in the `resolved` field. We just gave to map that together. Maybe it's worth introducing a native `Attachment` object at this point.

**Comment by Breq16** [comment]
Oh, the attachment *option* 🤦‍♀️ I misread that, my bad. Yep, it's not supported *yet,* but it'd be good for this library to have support for that.

**Comment by bat-glitch** [comment]
> Oh, the attachment _option_ 🤦‍♀️ I misread that, my bad. Yep, it's not supported _yet,_ but it'd be good for this library to have support for that.

I'm very excited for that, hopefully it gets added.

**Comment by justt-jay** [comment]
Could it be added, or it's not planned ?

**Comment by Breq16** [comment]
I'd agree that an `Attachment` model would be helpful.

Now might also be a good time to introduce a class for "outbound" attachments, similar to discord.py's `File`. I'm not really happy with how the library currently just uses aiohttp's tuple syntax directly. This would also be a good opportunity to get initial responses with attachments (using `multipart/form-data`) working.

**Comment by bat-glitch** [comment]
> I'd agree that an `Attachment` model would be helpful.
> 
> Now might also be a good time to introduce a class for "outbound" attachments, similar to discord.py's `File`. I'm not really happy with how the library currently just uses aiohttp's tuple syntax directly. This would also be a good opportunity to get initial responses with attachments (using `multipart/form-data`) working.

Will this be added soon?
