### ISSUE TITLE
Pull request template not working

### ISSUE THREAD

**Issue by therealr5** [Breq16/flask-discord-interactions#97]
**Describe the bug**
The pull request template appears to be broken and is not showing at all when opening any pull request. For my past requests, I always had to copy the file manually.

**Categorization**
This issue impacts...
- [ ] The library itself
- [ ] Documentation
- [ ] Examples
- [x] The repository itself

**Proposed change**
I'd suggest moving `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md` -> `.github/pull_request_template.md`. This should fix the issue

**Comment by Breq16** [comment]
Should hopefully be fixed in 813e20f1?

**Comment by therealr5** [comment]
Did a quick check. Works perfectly fine now. 
Thx for fixing
